name: bookstore_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"


flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/splash_logo.png
  color: "#ffffff"
  android_12:
    image: assets/splash_logo.png
    color: "#ffffff"


flutter:
  uses-material-design: true
