name: bookstore_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  hooks_riverpod: ^2.5.2
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"


flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/splash_logo.png
  color: "#ffffff"
  android_12:
    image: assets/splash_logo.png
    color: "#ffffff"


flutter:
  uses-material-design: true


  assets:
    - assets/images/